version: "3.8"
services:

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - ./data/redis:/var/lib/redis

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env

  meilisearch:
    image: getmeili/meilisearch:latest
    restart: always
    ports:
      - "7700:7700"
    volumes:
      - ./data/meilisearch:/data.ms
volumes:
  data: